# Site settings
title: 张健(Lane Zhang)'s technology blog
email: zjloveztt@gmail.com
description: "张健(Lane Zhang)，专注 Ruby, Python, JavaScript"
baseurl: ""
url: "https://github.com/gazeldx/gazeldx.github.io/blob/master/_posts/"
# twitter_username: jekyll
github_username:  gazeldx

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
